### ISSUE TITLE
station splits into chars

### ISSUE THREAD

**Issue by crotwell** [iris-edu/piqqa#6]
Ran as
```
python PIQQA.py --network=CO --stations=JSC --start=2022-06-01 --end=2022-07-01 
```
then piqqa produced this warning, note that the station in the url is `J,S,C` instead of `JSC`:
```
    INFO: Retrieving percent availability information for HHZ
         --> Unable to get measurements for percent_availability, waiting 5 seconds and trying again
             http://service.iris.edu/mustang/measurements/1/query?metric=percent_availability&net=CO&sta=J,S,C&loc=*&chan=HHZ&format=text&timewindow=2022-06-01,2022-07-01&nodata=404
         --> Still unable to get measurements for percent_availability, bypassing
**** WARNING: No Percent Availability found for HHZ - services could be down or metrics may not exist for data yet ****
```

**Comment by crotwell** [comment]
Perhaps related to first error, at the end I get:
```
Traceback (most recent call last):
  File "/Users/crotwell/dev/GitHub/iris-edu/piqqa/PIQQA.py", line 2182, in <module>
    main()
  File "/Users/crotwell/dev/GitHub/iris-edu/piqqa/PIQQA.py", line 2174, in main
    doReport( splitPlots, services, outfile, channels, network, startDate, endDate, tolerance, nTop, nBottom, metricList, startYear, endYear, actualChannels, avFilesDictionary, boxPlotExampleImage_moved, boxPlotDictionary, stations, locations, pdfDictionary, spectDictionary, mapFilename, metadataDF, availabilityType, metricsWithPlots, mapformat,includeOutliers, spectColorPalette, powerRanges, userDefinedPowerRange)
  File "/Users/crotwell/dev/GitHub/iris-edu/piqqa/PIQQA.py", line 1225, in doReport
    stationServiceLink = f'{stationServiceLink[:-1]}'
UnboundLocalError: local variable 'stationServiceLink' referenced before assignment
```

**Comment by laura-iris** [comment]
I can recreate this and am working on a fix that we should be able to include in the next release here soon.

**Comment by crotwell** [comment]
seems to work fine in 1.0.1, thanks.
